FEATURE: Allow dynamic newReferenceNodePath
psmb/Psmb.FlatNav pull request #3
Opened 2018-04-25 07:24 UTC by Sebobo

With this change the `newReferenceNodePath`
setting will be parsed with eel and is therefore
adjustable via a flowquery.

2018-04-25 09:37 UTC, Sebobo commented
Ok now it doesn't fetch it if the path starts with a "/".

I feel it's somehow a bit messy with the eel parsing, but I'm not sure how to improve it right now.
And I tried using actual eel in the Settings including the `${}` but for some reason it get's parsed immediately and creates an error. Then it would be easier to detect.

2018-04-25 09:53 UTC, dimaip commented on Resources/Private/FlatNav/src/FlatNav.js
> +        const contextPath = (this.props.newReferenceNodePath || this.props.preset.newReferenceNodePath) + '@' + context;
What happens when you try to create a node before the `fetchNewReferenceNodePath` has finished loading?
I'd block the "+" button until the request is complete.

2018-04-25 18:41 UTC, Sebobo commented
Plus button is now hidden while the reference path loads.

Is there any nice way to not define the whole preset state fully all the time?

2018-04-26 08:31 UTC, dimaip commented
> Is there any nice way to not define the whole preset state fully all the time?

Sure. E.g. use immutable data or deep merge. `setState` does shallow merge.
E.g. see https://stackoverflow.com/questions/24898012/react-js-setstate-overwriting-not-merging

The way I implemented it is obviously sloppy, was just a quick code jam.

2018-04-26 08:32 UTC, dimaip commented
> I feel it's somehow a bit messy with the eel parsing, but I'm not sure how to improve it right now.
And I tried using actual eel in the Settings including the ${} but for some reason it get's parsed immediately and creates an error. Then it would be easier to detect.

Yes, exactly, that's why I used Eel expressions without ${} originally.

2018-04-26 08:35 UTC, dimaip requested changes

2018-04-26 08:35 UTC, dimaip commented on Resources/Private/FlatNav/src/FlatNav.js
> +                }
perhaps the easiest fix not to overwrite everything is to use spread:

```
this.setState({
  [preset]: {
    ...this.state[preset],
    isLoadingReferenceNodePath: true
  }
})
```

2018-04-27 09:01 UTC, Sebobo commented
@dimaip thanks that made it much better and safer for future enhancements

2018-04-27 09:17 UTC, merged

2018-04-27 09:17 UTC, dimaip commented
Thanks!!!